### ISSUE TITLE
Please tag

### ISSUE THREAD

**Issue by xgqt** [sergeyklay/bnf-mode#19]
Please tag the release 0.4.5 to make it a little more easier for downstream (OS distributions maintainers) to package.

Thanks in advance!

Ref: https://github.com/sergeyklay/bnf-mode/commit/a4fe013fc945d8396930bc6d0dcc1cf9d7102f41

**Comment by sergeyklay** [comment]
Hello. I'll try to release new version ASAP. I'm sorry for the delay.

**Comment by sergeyklay** [comment]
I’m sorry completely ignoring this. There were good reasons for this, related to the war in my country. The issue has now been fixed. I created [0.4.5 tag](https://github.com/sergeyklay/bnf-mode/releases/tag/0.4.5) corresponding to the release in [GNU ELPA from 2021-Mar-18](https://elpa.gnu.org/packages/bnf-mode.html).

Please note, I have made some changes since then which will go into version 0.5.0. For more see https://github.com/sergeyklay/bnf-mode/compare/0.4.5...5aec2654

Thank you for your patience, and I’m sorry for the delay.

**Comment by xgqt** [comment]
I completely understand that, thanks a lot Serghei!
